# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # These packages are needed to build docs with image optimization
  jobs:
    post_create_environment:
      # Install uv
      - pip install uv
    post_install:
      # Install dependencies with 'docs' dependency group
      # - uv pip install .[docs]
      - uv pip install -r pyproject.toml
      # Using insiders versions of mkdocs-material & mkdocstrings
      - uv pip uninstall mkdocs-material # mkdocstrings mkdocstrings-python
      - uv pip install mkdocstrings mkdocstrings-python
      - uv pip install mkdocs-jupyter # This is bugged, I enforced it manually, let's see if it works

mkdocs:
  configuration: mkdocs.yml
